name: simple example
on:
  workflow_dispatch:
    inputs:
        os-choosen:
            required: true
            type: choice
            options:
              - ubuntu-latest
              - macos-latest

jobs:
  test1:
    runs-on: ["${{inputs.os-choosen}}"]
    steps:
      - run: echo "hello"
      - run: uname -a
      - name: print json of github
        env:
          jj: ${{ toJson(github) }}
        run: echo $jj
