name: simple example
on:
  workflow_dispatch:
    inputs:
        os-chosen:
          required: true
          type: choice
          options:
            - ubuntu-latest
            - macOS
jobs:
  test1:
    runs-on: unbuntu-latest
    steps:
      - run: echo "hello"
      - run: uname -a
