name: simple example
on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: windows-latest
    steps:
      - run: echo "hello"
      - run:  cl -h
      - name: print json of github
        env:
          jj: ${{ toJson(github) }}
        run: echo $jj
