name: AI Inference Workflow
on:
 workflow_dispatch: # Allows manual triggering of the workflow
  inputs:
     prompt:
       description:  "input prompt"
       required: true
       type: string
       default: "What is the capital of France?"
   
jobs:
 inference:
   runs-on: ubuntu-latest
   permissions:
     models: read # Required for accessing AI models
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
     - name: Run AI Inference
       id: inference
       uses: actions/ai-inference@v1
       with:
         prompt: ${{ inputs.prompt }}
         max-tokens: 15000 
     - name: Display Output
       run: |
         echo "AI Response ${{ steps.inference.outputs.response-file }}"
         cat "${{steps.inference.outputs.response-file}}"
