name: "test1"
on: 
  push:
  workflow_dispatch:
jobs:
  job1:
    strategy:
      matrix:
        version: [20,18]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.version}}
        - run: node --version
          shell: bash