name: "test1"
on: 
  push:
  workflow_dispatch:
jobs:
  job1:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4
        - run: |
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
            cl.exe a.cpp
            ./a.exe
          shell: cmd